controllers:
    resource: ../src/Controller/
    type: attribute
app_logout:
    path: /logout
    methods: GET
login:
    path: /
    controller: App\Controller\SecurityController::login
    schemes: [https]
