controllers:
    resource: ../src/Controller/
    type: attribute
    defaults:
        schemes: [https]
app_logout:
    path: /logout
    methods: GET
login:
    path: /
    controller: App\Controller\SecurityController::login
    schemes: [https]
